import { Assessment } from '../types/index.ts';
import jsPDF from 'jspdf';
import { saveAs } from 'file-saver';

// Format timestamp to readable date
const formatDate = (timestamp: number): string => {
  return new Date(timestamp).toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
};

// Generate Markdown report
export const generateMarkdownReport = (assessment: Assessment): string => {
  const { modelInput, printerMaterial, riskLevel, confidence, riskFactors, printPlan } = assessment;

  let markdown = `# 3D Print Plan Report\n\n`;
  markdown += `**Assessment ID:** ${assessment.id}\n`;
  markdown += `**Date:** ${formatDate(assessment.timestamp)}\n`;
  markdown += `**Generated by:** [Print Risk Checker](https://github.com/yourusername/print-risk-checker)\n\n`;

  markdown += `---\n\n`;

  // Model Information
  markdown += `## Model Information\n\n`;
  markdown += `- **Name:** ${modelInput.modelName}\n`;
  if (modelInput.modelLink) {
    markdown += `- **Link:** ${modelInput.modelLink}\n`;
  }
  markdown += `- **Intended Use:** ${modelInput.intendedUse}\n`;
  markdown += `- **Dimensions:** ${modelInput.boundingBox.x} × ${modelInput.boundingBox.y} × ${modelInput.boundingBox.z} mm\n`;
  if (typeof modelInput.minWallThickness === 'number') {
    markdown += `- **Min Wall Thickness:** ${modelInput.minWallThickness}mm\n`;
  }
  markdown += `- **Flat Base:** ${modelInput.flatBase || 'unknown'}\n`;
  markdown += `- **Overhangs:** ${modelInput.overhangs || 'unknown'}\n`;
  markdown += `- **Bridges:** ${modelInput.bridges || 'unknown'}\n\n`;

  // Printer & Material
  markdown += `## Printer & Material Setup\n\n`;
  markdown += `- **Material:** ${printerMaterial.material}\n`;
  markdown += `- **Nozzle Size:** ${printerMaterial.nozzleSize}mm\n`;
  markdown += `- **Layer Height:** ${printerMaterial.layerHeight}mm\n`;
  markdown += `- **Supports:** ${printerMaterial.supportsAllowed ? 'Enabled' : 'Disabled'}\n`;
  markdown += `- **Priority:** ${printerMaterial.priority}\n`;
  if (printerMaterial.bedSize) {
    markdown += `- **Bed Size:** ${printerMaterial.bedSize.x} × ${printerMaterial.bedSize.y} × ${printerMaterial.bedSize.z} mm\n`;
  }
  markdown += `\n`;

  // Risk Assessment
  markdown += `## Risk Assessment\n\n`;
  markdown += `**Overall Risk:** ${riskLevel.toUpperCase()}\n\n`;
  markdown += `**Confidence Level:** ${confidence.charAt(0).toUpperCase() + confidence.slice(1)}\n\n`;

  markdown += `### Risk Factors\n\n`;
  if (riskFactors.length === 0) {
    markdown += `- No significant risks identified\n\n`;
  } else {
    riskFactors.forEach((factor, index) => {
      markdown += `${index + 1}. **[${factor.severity.toUpperCase()}]** ${factor.message}\n`;
      if (factor.mitigation) {
        markdown += `   - *Mitigation:* ${factor.mitigation}\n`;
      }
    });
    markdown += `\n`;
  }

  // Print Plan
  markdown += `## Recommended Print Plan\n\n`;

  markdown += `### Orientation\n`;
  markdown += `${printPlan.orientation}\n\n`;

  markdown += `### Supports\n`;
  markdown += `- **Enabled:** ${printPlan.supports.enabled ? 'Yes' : 'No'}\n`;
  markdown += `- **Details:** ${printPlan.supports.details}\n\n`;

  markdown += `### Print Settings\n`;
  markdown += `- **Walls/Perimeters:** ${printPlan.walls}\n`;
  markdown += `- **Infill:** ${printPlan.infill.percentage}% ${printPlan.infill.pattern}\n`;
  markdown += `- **Bed Adhesion:** ${printPlan.adhesion === 'none' ? 'None required' : printPlan.adhesion.charAt(0).toUpperCase() + printPlan.adhesion.slice(1)}\n\n`;

  markdown += `### Speed Recommendations\n`;
  markdown += `${printPlan.speedNotes}\n\n`;

  markdown += `### Material Notes\n`;
  markdown += `${printPlan.materialNotes}\n\n`;

  // Pre-Flight Checklist
  markdown += `## Pre-Flight Checklist\n\n`;
  printPlan.mitigationChecklist.forEach((item) => {
    markdown += `- [ ] ${item}\n`;
  });
  markdown += `\n`;

  // Limitations
  markdown += `---\n\n`;
  markdown += `## Limitations & Disclaimer\n\n`;
  markdown += `This assessment is based on the information provided and uses rule-based heuristics. `;
  markdown += `Actual print success depends on many factors including: printer calibration, `;
  markdown += `filament quality, environmental conditions, and slicer settings. `;
  markdown += `Always monitor your first few layers and adjust as needed.\n\n`;
  markdown += `**Recommendation:** If this is your first time printing this model or using these settings, `;
  markdown += `consider running a small test print or scaling down the model first.\n\n`;

  markdown += `---\n\n`;
  markdown += `*Report generated by Print Risk Checker - Your 3D printing pre-flight assistant*\n`;

  return markdown;
};

// Download Markdown report
export const downloadMarkdownReport = (assessment: Assessment): void => {
  const markdown = generateMarkdownReport(assessment);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const filename = `print-plan-${assessment.modelInput.modelName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${assessment.id}.md`;
  saveAs(blob, filename);
};

// Generate PDF report
export const generatePDFReport = (assessment: Assessment): void => {
  const doc = new jsPDF();
  const { modelInput, printerMaterial, riskLevel, confidence, riskFactors, printPlan } = assessment;

  let y = 20;
  const lineHeight = 7;
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;

  // Helper to add text with word wrap
  const addText = (text: string, x: number, fontSize: number = 10, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, x, y);
    y += lines.length * lineHeight;
  };

  // Helper to check if new page needed
  const checkPageBreak = (neededSpace: number = 20) => {
    if (y + neededSpace > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
  };

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('3D Print Plan Report', margin, y);
  y += 12;

  // Metadata
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(`Assessment ID: ${assessment.id}`, margin, y);
  y += 5;
  doc.text(`Date: ${formatDate(assessment.timestamp)}`, margin, y);
  y += 10;
  doc.setTextColor(0);

  // Risk Badge
  checkPageBreak(30);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Risk Assessment:', margin, y);

  // Color-coded risk level
  const riskColors: { [key: string]: [number, number, number] } = {
    low: [34, 197, 94],
    medium: [234, 179, 8],
    high: [239, 68, 68],
  };

  y += 7;
  doc.setFillColor(...riskColors[riskLevel]);
  doc.roundedRect(margin, y - 5, 50, 10, 2, 2, 'F');
  doc.setTextColor(255);
  doc.setFontSize(11);
  doc.text(riskLevel.toUpperCase(), margin + 25, y, { align: 'center' });
  doc.setTextColor(0);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Confidence: ${confidence.charAt(0).toUpperCase() + confidence.slice(1)}`, margin + 55, y);
  y += 15;

  // Model Information
  checkPageBreak();
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Model Information', margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  addText(`Name: ${modelInput.modelName}`, margin);
  if (modelInput.modelLink) {
    addText(`Link: ${modelInput.modelLink}`, margin);
  }
  addText(`Intended Use: ${modelInput.intendedUse}`, margin);
  addText(`Dimensions: ${modelInput.boundingBox.x} × ${modelInput.boundingBox.y} × ${modelInput.boundingBox.z} mm`, margin);
  y += 5;

  // Printer & Material
  checkPageBreak();
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Printer & Material', margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  addText(`Material: ${printerMaterial.material}`, margin);
  addText(`Nozzle: ${printerMaterial.nozzleSize}mm, Layer Height: ${printerMaterial.layerHeight}mm`, margin);
  addText(`Supports: ${printerMaterial.supportsAllowed ? 'Enabled' : 'Disabled'}`, margin);
  y += 5;

  // Risk Factors
  checkPageBreak(30);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Risk Factors', margin, y);
  y += 8;

  doc.setFontSize(9);
  if (riskFactors.length === 0) {
    doc.setFont('helvetica', 'normal');
    addText('No significant risks identified', margin, 9);
  } else {
    riskFactors.forEach((factor, index) => {
      checkPageBreak(15);
      doc.setFont('helvetica', 'bold');
      const severityColors: { [key: string]: [number, number, number] } = {
        low: [100, 100, 100],
        medium: [200, 120, 0],
        high: [200, 0, 0],
      };
      doc.setTextColor(...severityColors[factor.severity]);
      doc.text(`[${factor.severity.toUpperCase()}]`, margin, y);
      doc.setTextColor(0);
      doc.setFont('helvetica', 'normal');
      addText(`${index + 1}. ${factor.message}`, margin + 25, 9);
    });
  }
  y += 5;

  // Print Plan
  checkPageBreak(40);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Recommended Print Plan', margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Orientation:', margin, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  addText(printPlan.orientation, margin);
  y += 3;

  checkPageBreak(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Settings:', margin, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  addText(`Walls: ${printPlan.walls} | Infill: ${printPlan.infill.percentage}% ${printPlan.infill.pattern}`, margin);
  addText(`Adhesion: ${printPlan.adhesion === 'none' ? 'None' : printPlan.adhesion}`, margin);
  y += 3;

  checkPageBreak(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Speed & Material Notes:', margin, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  addText(printPlan.speedNotes, margin, 9);
  addText(printPlan.materialNotes, margin, 9);
  y += 5;

  // Checklist
  checkPageBreak(30);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Pre-Flight Checklist', margin, y);
  y += 7;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  printPlan.mitigationChecklist.forEach((item) => {
    checkPageBreak(10);
    doc.rect(margin, y - 3, 3, 3);
    addText(item, margin + 6, 9);
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(100);
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.text('Generated by Print Risk Checker - 3D Printing Pre-Flight Assistant', pageWidth / 2, footerY, { align: 'center' });

  // Save PDF
  const filename = `print-plan-${modelInput.modelName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${assessment.id}.pdf`;
  doc.save(filename);
};
